// VHDL generator — synthesizable entity + dataflow architecture from the
// minimized SOP expression produced by quine-mccluskey.
import { minimize } from './quine-mccluskey.js';

export function generateVhdl(outputs, nVars, varNames) {
    const minterms = [];
    outputs.forEach((v, i) => { if (v === 1) minterms.push(i); });
    const result = minimize([...minterms], nVars, varNames);

    let expr;
    if (result.sop === '0') expr = "'0'";
    else if (result.sop === '1') expr = "'1'";
    else expr = result.vhdlExpr;

    const ports = varNames.map(v => `        ${v} : in  std_logic`).join(';\n');

    return `library ieee;
use ieee.std_logic_1164.all;

-- Auto-generated by GEII Digital Lab
-- Minimal SOP:  S = ${result.sop}
entity logic_fn is
    port (
${ports};
        S : out std_logic
    );
end entity logic_fn;

architecture dataflow of logic_fn is
begin
    S <= ${expr};
end architecture dataflow;
`;
}
